#
# host machine
#   physical process as container  
#     logical site as a thread
# site --> process --> host
#   
# site: logical site (either as server/coordinator), which lives in a thread (may share thread 
# process 
# host is  

# site - partition map
site:
  server: # each line is a partition
#    - ["s101:8881", "s201:8882", "s301:8883"]
#    - ["s102:8884", "s202:8885", "s302:8886"]
    - ["s101:8881"]
#    - ["s102:8884"]
  client: # each line is a partition
#     - ["c1"]
    - ["c1", "c2"]
    - ["c3", "c4"]

# site - process map
process:
  s101: localhost
#  s102: localhost
#  s201: localhost
#  s202: localhost
#  s301: localhost
#  s302: localhost
  c1: localhost
  c2: localhost
  c3: localhost
  c4: localhost

# process - host map
host:
  localhost: 127.0.0.1

mode:
  cc: 2pl_ww # concurrency control
  read_only: occ
  batch: false
  retry: 0
  ongoing: 1 # per client


bench:
  workload: tpccd #sharded by district
  scale: 1
  weight:
    new_order: 44
    payment : 44
    delivery: 4
    order_status: 4
    stock_level: 4
  population: # intial number of records in each table
    warehouse: 1
    district: 10
    customer: 30000
    history: 30000
    order: 30000
    new_order: 9000
    item: 100000
    stock: 100000
    order_line: 300000

schema: # schema
  - name: warehouse
    primary: w_id
    column:
      - name: w_id
        type: integer
      - name: w_name
        type: string
      - name: w_street_1
        type: string
      - name: w_street_2
        type: string
      - name: w_city
        type: string
      - name: w_state
        type: string
      - name: w_zip
        type: string
      - name: w_tax
        type: double
      - name: w_ytd
        type: double
  - name: district
    primary: d_id, d_w_id
    column:
      - {name: d_id,        type: integer}
      - {name: d_w_id,      type: integer, foreign: warehouse.w_id}
      - {name: d_name,      type: string}
      - {name: d_street_1,  type: string}
      - {name: d_street_2,  type: string}
      - {name: d_city,      type: string}
      - {name: d_zip,       type: string}
      - {name: d_tax,       type: double}
      - {name: d_ytd,       type: double}
      - {name: d_next_o_id, type: string}
  - name: customer
    primary: c_id, c_d_id, c_w_id
    column:
      - {name: c_id,        type: integer}
      - {name: c_d_id,      type: integer}
      - {name: c_w_id,      type: integer}
      - {name: c_first,     type: string}
      - {name: c_middle,    type: string}
      - {name: c_last,      type: string}
      - {name: c_street_1,  type: string}
      - {name: c_street_2,  type: string}
      - {name: c_city,      type: string}
      - {name: c_state,     type: string}
      - {name: c_zip,       type: string}
      - {name: c_phone,     type: string}
      - {name: c_since,     type: string}
      - {name: c_credit,    type: string}
      - {name: c_credit_lim,    type: double}
      - {name: c_discount,      type: double}
      - {name: c_balance,       type: double}
      - {name: c_ytd_payment,   type: double}
      - {name: c_payment_cnt,   type: integer}
      - {name: c_delivery_cnt,  type: integer}
      - {name: c_data,          type: string}
  - name: history
    column:
      - {name: h_key, type: integer}
      - {name: h_c_id,  type: integer, foreign: customer.c_id}
      - {name: h_c_d_id, type: integer, foreign: customer.c_d_id}
      - {name: h_c_w_id, type: integer, foreign: customer.c_w_id}
      - {name: h_d_id, type: integer, foreign: district.d_id}
      - {name: h_w_id, type: integer, foreign: district.d_w_id}
      - {name: h_date, type: integer}
      - {name: h_amount, type: double}
      - {name: h_data, type: string}
  - name: order
    primary: o_d_id, o_w_id
    column:
      - {name: o_d_id, type: integer}
      - {name: o_w_id, type: integer}
      - {name: o_id, type: integer}
      - {name: o_c_id, type: integer, foreign: customer.c_id}
      - {name: o_entry_d, type: string}
      - {name: o_carrier_id, type: integer}
      - {name: o_ol_cnt, type: integer}
      - {name: o_all_local, type: integer}
  - name: new_order
    primary: no_d_id, no_w_id, no_o_id
    column:
      - {name: no_d_id, type: integer, foreign: order.o_d_id}
      - {name: no_w_id, type: integer, foreign: order.o_w_id}
      - {name: no_o_id, type: integer, foreign: order.o_id}
  - name: item
    primary: i_id
    column:
      - {name: i_id,    type: integer}
      - {name: i_im_id, type: integer}
      - {name: i_name,  type: string}
      - {name: i_price, type: double}
      - {name: i_data,  type: string}
  - name: stock
    primary: s_i_id, s_w_id,
    column:
      - {name: s_i_id,    type: integer, foreign: item.i_id}
      - {name: s_w_id,    type: integer, foreign: warehouse.w_id}
      - {name: s_quantity,type: integer}
      - {name: s_dist_01, type: string}
      - {name: s_dist_02, type: string}
      - {name: s_dist_03, type: string}
      - {name: s_dist_04, type: string}
      - {name: s_dist_05, type: string}
      - {name: s_dist_06, type: string}
      - {name: s_dist_07, type: string}
      - {name: s_dist_07, type: string}
      - {name: s_dist_08, type: string}
      - {name: s_dist_09, type: string}
      - {name: s_dist_10, type: string}
  - name: order_line
    primary: ol_d_id, ol_w_id, ol_o_id, ol_number
    column:
      - {name: ol_d_id,   type: integer}
      - {name: ol_w_id,   type: integer}
      - {name: ol_o_id,   type: integer}
      - {name: ol_number, type: integer}
      - {name: ol_i_id,   type: integer, foreign: stock.s_i_id}
      - {name: ol_supply_w_id,  type: integer, foreign: stock.s_w_id}
      - {name: ol_delivery_d,   type: string}
      - {name: ol_quantity,     type: string}
      - {name: ol_amount,       type: double}
      - {name: ol_dist_info,    type: string}

# sharding strategy.
# default is MOD by primary key.
# CUSTOM means strategy is defined in the code.
# TODO a better way to define sharding strategy.
sharding:
  warehouse:  MOD
  district:   MOD
  customer:   CUSTOM
  history:    MOD
  order:      MOD
  new_order:  MOD
  item:       MOD
  stock:      MOD
  order_line: MOD

